# -*- coding: utf-8 -*-
"""HTML QUICK STYLER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/117pgOPE6yy7-l8YFyJcffmQQ65edC7l2
"""

!pip install -U transformers

# Use a pipeline as a high-level helper

from transformers import pipeline

pipe = pipeline("text-generation", model="ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role": "user", "content": "Who are you?"},

]

pipe(messages)

import gradio as gr
from datetime import datetime
from typing import Tuple, Dict, List
import html

# HTML QUICK-STYLER - ADVANCED VERSION (WITH LIVE PREVIEW, COLOR SWATCHES & THEME TOGGLE)
class ColorPaletteGenerator:
    """Generate visually cohesive color palettes"""

    @staticmethod
    def generate_palette(style: str = "modern") -> Dict[str, str]:
        """Generate a cohesive color palette based on style"""
        palettes = {
            'modern': {
                'primary': '#667eea',
                'secondary': '#764ba2',
                'accent': '#f093fb',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'vibrant': {
                'primary': '#ff6b6b',
                'secondary': '#ff8e72',
                'accent': '#f5576c',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'ocean': {
                'primary': '#0099cc',
                'secondary': '#006699',
                'accent': '#00ccff',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'forest': {
                'primary': '#27ae60',
                'secondary': '#1e8449',
                'accent': '#52be80',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'sunset': {
                'primary': '#ff8c42',
                'secondary': '#ff6b35',
                'accent': '#ffa751',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'luxury': {
                'primary': '#1a1a1a',
                'secondary': '#333333',
                'accent': '#FFD700',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'creative': {
                'primary': '#9b59b6',
                'secondary': '#8e44ad',
                'accent': '#e74c3c',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'minimal': {
                'primary': '#2c3e50',
                'secondary': '#34495e',
                'accent': '#3498db',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            }
        }
        return palettes.get(style.lower(), palettes['modern'])

    @staticmethod
    def get_light_palette(dark_palette: Dict[str, str]) -> Dict[str, str]:
        """Generate a light variant from a dark palette"""
        return {
            'primary': dark_palette['primary'],
            'secondary': dark_palette['secondary'],
            'accent': dark_palette['accent'],
            'background': '#f8fafc',
            'surface': '#ffffff',
            'text_primary': '#0f172a',
            'text_secondary': '#334155',
            'border': '#cbd5e1'
        }


class HTMLPageBuilder:
    """Build styled HTML pages from descriptions"""

    @staticmethod
    def extract_sections(description: str) -> List[str]:
        """Extract sections from description"""
        sections = []
        section_keywords = {
            'hero': ['hero', 'banner', 'landing'],
            'features': ['features', 'services', 'benefits'],
            'about': ['about', 'team', 'company'],
            'portfolio': ['portfolio', 'gallery', 'work', 'projects'],
            'testimonials': ['testimonial', 'reviews', 'feedback'],
            'pricing': ['pricing', 'plans', 'cost'],
            'contact': ['contact', 'form', 'reach'],
            'footer': ['footer', 'bottom']
        }

        desc_lower = description.lower()
        for section_type, keywords in section_keywords.items():
            for keyword in keywords:
                if keyword in desc_lower:
                    sections.append(section_type)
                    break

        if not sections:
            sections = ['hero', 'features', 'contact', 'footer']

        # Remove duplicates while preserving order
        unique_sections = []
        for section in sections:
            if section not in unique_sections:
                unique_sections.append(section)

        return unique_sections

    @staticmethod
    def generate_meta_tags(title: str, description: str) -> str:
        """Generate SEO meta tags"""
        return f'''    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <meta name="description" content="{description[:160]}">
    <meta name="theme-color" content="#0f172a">
    <meta property="og:title" content="{title}">
    <meta property="og:description" content="{description[:160]}">
    <meta property="og:type" content="website">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="author" content="HTML Quick-Styler">'''

    @staticmethod
    def generate_section_html(section_type: str, palette: Dict) -> str:
        """Generate HTML for specific section with an id attribute"""
        # Map section type to a readable name for the id
        section_id = section_type
        sections = {
            'hero': f'''
    <section id="{section_id}" class="hero">
        <div class="hero-content">
            <h1>Welcome to Your Site</h1>
            <p>Create amazing web experiences</p>
            <button class="btn btn-primary">Get Started</button>
        </div>
    </section>''',

            'features': f'''
    <section id="{section_id}" class="features">
        <h2>Features</h2>
        <div class="features-grid">
            <div class="feature-card">
                <h3>Fast</h3>
                <p>Lightning-quick performance</p>
            </div>
            <div class="feature-card">
                <h3>Secure</h3>
                <p>Enterprise-grade security</p>
            </div>
            <div class="feature-card">
                <h3>Scalable</h3>
                <p>Grow without limits</p>
            </div>
        </div>
    </section>''',

            'about': f'''
    <section id="{section_id}" class="about">
        <div class="about-content">
            <h2>About Us</h2>
            <p>We're passionate about creating beautiful, functional websites that help your business grow.</p>
        </div>
    </section>''',

            'portfolio': f'''
    <section id="{section_id}" class="portfolio">
        <h2>Our Work</h2>
        <div class="portfolio-grid">
            <div class="portfolio-item"></div>
            <div class="portfolio-item"></div>
            <div class="portfolio-item"></div>
        </div>
    </section>''',

            'testimonials': f'''
    <section id="{section_id}" class="testimonials">
        <h2>What People Say</h2>
        <div class="testimonials-grid">
            <div class="testimonial">
                <p>"Amazing service!"</p>
                <span>- Client Name</span>
            </div>
            <div class="testimonial">
                <p>"Highly recommended!"</p>
                <span>- Happy Customer</span>
            </div>
        </div>
    </section>''',

            'pricing': f'''
    <section id="{section_id}" class="pricing">
        <h2>Pricing Plans</h2>
        <div class="pricing-grid">
            <div class="pricing-card">
                <h3>Starter</h3>
                <p class="price">$29</p>
                <ul>
                    <li>Feature 1</li>
                    <li>Feature 2</li>
                    <li>Basic Support</li>
                </ul>
                <button class="btn btn-secondary">Choose Plan</button>
            </div>
            <div class="pricing-card featured">
                <h3>Pro</h3>
                <p class="price">$79</p>
                <ul>
                    <li>All Starter Features</li>
                    <li>Advanced Features</li>
                    <li>Priority Support</li>
                </ul>
                <button class="btn btn-primary">Choose Plan</button>
            </div>
            <div class="pricing-card">
                <h3>Enterprise</h3>
                <p class="price">$199</p>
                <ul>
                    <li>All Pro Features</li>
                    <li>Custom Solutions</li>
                    <li>24/7 Support</li>
                </ul>
                <button class="btn btn-secondary">Contact Us</button>
            </div>
        </div>
    </section>''',

            'contact': f'''
    <section id="{section_id}" class="contact">
        <h2>Contact Us</h2>
        <form class="contact-form">
            <input type="text" placeholder="Your Name" required>
            <input type="email" placeholder="Your Email" required>
            <textarea placeholder="Your Message" rows="5" required></textarea>
            <button type="submit" class="btn btn-primary">Send Message</button>
        </form>
    </section>''',

            'footer': f'''
    <footer id="{section_id}">
        <div class="footer-content">
            <p>&copy; 2024 Your Company. All rights reserved.</p>
            <div class="footer-links">
                <a href="#">Privacy Policy</a>
                <a href="#">Terms of Service</a>
                <a href="#">Contact</a>
            </div>
        </div>
    </footer>'''
        }

        return sections.get(section_type, '')

    @staticmethod
    def generate_nav_links(sections: List[str]) -> str:
        """Generate navigation links based on sections present"""
        # Map section names to display text
        display_names = {
            'hero': 'Home',
            'features': 'Features',
            'about': 'About',
            'portfolio': 'Work',
            'testimonials': 'Testimonials',
            'pricing': 'Pricing',
            'contact': 'Contact'
        }
        links = []
        for section in sections:
            if section in display_names and section != 'footer':  # footer not in nav
                links.append(f'<a href="#{section}">{display_names[section]}</a>')
        return '\n                '.join(links)

    @staticmethod
    def generate_css(dark_palette: Dict, light_palette: Dict = None) -> str:
        """Generate comprehensive CSS with dark/light theme support"""
        if light_palette is None:
            light_palette = ColorPaletteGenerator.get_light_palette(dark_palette)

        return f'''    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}

        :root {{
            --primary: {dark_palette['primary']};
            --secondary: {dark_palette['secondary']};
            --accent: {dark_palette['accent']};
            --background: {dark_palette['background']};
            --surface: {dark_palette['surface']};
            --text-primary: {dark_palette['text_primary']};
            --text-secondary: {dark_palette['text_secondary']};
            --border: {dark_palette['border']};
        }}

        body.light-mode {{
            --primary: {light_palette['primary']};
            --secondary: {light_palette['secondary']};
            --accent: {light_palette['accent']};
            --background: {light_palette['background']};
            --surface: {light_palette['surface']};
            --text-primary: {light_palette['text_primary']};
            --text-secondary: {light_palette['text_secondary']};
            --border: {light_palette['border']};
        }}

        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, var(--background) 0%, var(--surface) 100%);
            color: var(--text-primary);
            line-height: 1.6;
            min-height: 100vh;
            transition: background-color 0.3s, color 0.3s;
        }}

        /* Theme toggle button */
        .theme-toggle {{
            position: fixed;
            bottom: 20px;
            right: 20px;
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 50px;
            padding: 10px 15px;
            cursor: pointer;
            z-index: 1000;
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
            color: var(--text-primary);
            font-size: 1.2rem;
            transition: all 0.3s;
        }}
        .theme-toggle:hover {{
            transform: scale(1.1);
            border-color: var(--primary);
        }}

        header {{
            background: rgba(15, 23, 42, 0.95);
            backdrop-filter: blur(10px);
            padding: 1.5rem 2rem;
            position: sticky;
            top: 0;
            z-index: 100;
            border-bottom: 1px solid var(--border);
        }}

        header nav {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            max-width: 1200px;
            margin: 0 auto;
        }}

        header h1 {{
            font-size: 1.8rem;
            background: linear-gradient(135deg, var(--primary), var(--accent));
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }}

        header nav a {{
            color: var(--text-secondary);
            text-decoration: none;
            margin: 0 1.5rem;
            transition: color 0.3s ease;
        }}

        header nav a:hover {{
            color: var(--primary);
        }}

        main {{
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 2rem;
        }}

        section {{
            padding: 4rem 0;
            animation: fadeIn 0.6s ease-in;
        }}

        @keyframes fadeIn {{
            from {{
                opacity: 0;
                transform: translateY(20px);
            }}
            to {{
                opacity: 1;
                transform: translateY(0);
            }}
        }}

        h1, h2, h3 {{
            color: var(--text-primary);
            margin-bottom: 1rem;
        }}

        h1 {{
            font-size: 3rem;
            font-weight: 700;
        }}

        h2 {{
            font-size: 2rem;
            margin-bottom: 2rem;
            text-align: center;
        }}

        h3 {{
            font-size: 1.3rem;
        }}

        .hero {{
            background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%);
            color: white;
            padding: 6rem 0;
            text-align: center;
            min-height: 500px;
            display: flex;
            align-items: center;
            justify-content: center;
            border-radius: 20px;
            margin-top: 2rem;
        }}

        .hero h1 {{
            color: white;
            font-size: 4rem;
            margin-bottom: 1rem;
            animation: slideDown 0.8s ease;
        }}

        .hero p {{
            font-size: 1.5rem;
            margin-bottom: 2rem;
            opacity: 0.95;
            animation: slideUp 0.8s ease;
        }}

        @keyframes slideDown {{
            from {{
                opacity: 0;
                transform: translateY(-30px);
            }}
            to {{
                opacity: 1;
                transform: translateY(0);
            }}
        }}

        @keyframes slideUp {{
            from {{
                opacity: 0;
                transform: translateY(30px);
            }}
            to {{
                opacity: 1;
                transform: translateY(0);
            }}
        }}

        .btn {{
            padding: 0.8rem 2rem;
            border: none;
            border-radius: 8px;
            font-size: 1rem;
            cursor: pointer;
            transition: all 0.3s ease;
            font-weight: 600;
        }}

        .btn-primary {{
            background: var(--primary);
            color: white;
        }}

        .btn-primary:hover {{
            background: var(--secondary);
            transform: translateY(-2px);
            box-shadow: 0 10px 20px rgba(0,0,0,0.2);
        }}

        .btn-secondary {{
            background: transparent;
            color: var(--primary);
            border: 2px solid var(--primary);
        }}

        .btn-secondary:hover {{
            background: var(--primary);
            color: white;
            transform: translateY(-2px);
        }}

        .features-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 2rem;
        }}

        .feature-card {{
            background: rgba(30, 41, 59, 0.8);
            padding: 2rem;
            border-radius: 12px;
            border: 1px solid var(--border);
            transition: all 0.3s ease;
            backdrop-filter: blur(10px);
        }}

        .feature-card:hover {{
            transform: translateY(-8px);
            border-color: var(--primary);
            box-shadow: 0 20px 40px rgba(0,0,0,0.3);
        }}

        .feature-card h3 {{
            color: var(--primary);
            margin-bottom: 0.5rem;
        }}

        .feature-card p {{
            color: var(--text-secondary);
        }}

        .portfolio-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
            gap: 2rem;
        }}

        .portfolio-item {{
            aspect-ratio: 1;
            background: linear-gradient(135deg, var(--primary), var(--secondary));
            border-radius: 12px;
            cursor: pointer;
            transition: all 0.3s ease;
            border: 1px solid var(--border);
        }}

        .portfolio-item:hover {{
            transform: scale(1.05);
            box-shadow: 0 20px 40px rgba(0,0,0,0.3);
        }}

        .testimonials-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 2rem;
        }}

        .testimonial {{
            background: rgba(30, 41, 59, 0.8);
            padding: 2rem;
            border-left: 4px solid var(--primary);
            border-radius: 8px;
        }}

        .testimonial p {{
            font-style: italic;
            margin-bottom: 1rem;
            color: var(--text-secondary);
        }}

        .testimonial span {{
            font-weight: 600;
            color: var(--primary);
        }}

        .pricing-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
            gap: 2rem;
        }}

        .pricing-card {{
            background: rgba(30, 41, 59, 0.8);
            padding: 2rem;
            border-radius: 12px;
            border: 1px solid var(--border);
            text-align: center;
            transition: all 0.3s ease;
        }}

        .pricing-card.featured {{
            border: 2px solid var(--primary);
            transform: scale(1.05);
            box-shadow: 0 20px 40px rgba(0,0,0,0.3);
        }}

        .pricing-card:hover {{
            transform: translateY(-8px);
            border-color: var(--primary);
        }}

        .pricing-card.featured:hover {{
            transform: scale(1.05) translateY(-8px);
        }}

        .price {{
            font-size: 2.5rem;
            font-weight: 700;
            color: var(--primary);
            margin: 1rem 0;
        }}

        .pricing-card ul {{
            list-style: none;
            margin: 1.5rem 0;
            text-align: left;
            padding: 0 1rem;
        }}

        .pricing-card li {{
            padding: 0.5rem 0;
            color: var(--text-secondary);
        }}

        .pricing-card li::before {{
            content: "✓";
            color: var(--primary);
            margin-right: 0.5rem;
            font-weight: bold;
        }}

        .contact {{
            max-width: 600px;
            margin: 0 auto;
        }}

        .contact-form {{
            display: flex;
            flex-direction: column;
            gap: 1rem;
        }}

        .contact-form input,
        .contact-form textarea {{
            padding: 1rem;
            background: rgba(30, 41, 59, 0.8);
            border: 1px solid var(--border);
            border-radius: 8px;
            color: var(--text-primary);
            font-size: 1rem;
            transition: all 0.3s ease;
        }}

        .contact-form input:focus,
        .contact-form textarea:focus {{
            outline: none;
            border-color: var(--primary);
            box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);
        }}

        .contact-form input::placeholder,
        .contact-form textarea::placeholder {{
            color: var(--text-secondary);
        }}

        footer {{
            background: rgba(15, 23, 42, 0.95);
            padding: 3rem 0;
            margin-top: 4rem;
            border-top: 1px solid var(--border);
        }}

        .footer-content {{
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 2rem;
            display: flex;
            justify-content: space-between;
            align-items: center;
            flex-wrap: wrap;
            gap: 2rem;
        }}

        .footer-links {{
            display: flex;
            gap: 2rem;
        }}

        .footer-links a {{
            color: var(--text-secondary);
            text-decoration: none;
            transition: color 0.3s ease;
        }}

        .footer-links a:hover {{
            color: var(--primary);
        }}

        @media (max-width: 768px) {{
            header nav {{
                flex-direction: column;
                gap: 1rem;
            }}

            header h1 {{
                font-size: 1.4rem;
            }}

            .hero h1 {{
                font-size: 2rem;
            }}

            .hero p {{
                font-size: 1.1rem;
            }}

            .footer-content {{
                flex-direction: column;
                text-align: center;
            }}

            .pricing-card.featured {{
                transform: scale(1);
            }}

            .pricing-card.featured:hover {{
                transform: translateY(-8px);
            }}
        }}
    </style>'''

    @staticmethod
    def generate_theme_toggle_script() -> str:
        """Generate JavaScript for the theme toggle button"""
        return '''
    <!-- Theme toggle button and script -->
    <button class="theme-toggle" id="themeToggle" aria-label="Toggle dark/light mode">🌙</button>
    <script>
        (function() {
            const toggle = document.getElementById('themeToggle');
            const body = document.body;

            // Check for saved preference
            const savedTheme = localStorage.getItem('theme');
            if (savedTheme === 'light') {
                body.classList.add('light-mode');
                toggle.textContent = '☀️';
            }

            toggle.addEventListener('click', () => {
                body.classList.toggle('light-mode');
                const isLight = body.classList.contains('light-mode');
                toggle.textContent = isLight ? '☀️' : '🌙';
                localStorage.setItem('theme', isLight ? 'light' : 'dark');
            });
        })();
    </script>
        '''


class HTMLGenerationEngine:
    """Main engine for HTML page generation"""

    @staticmethod
    def generate_page(title: str, description: str, style: str = "modern", include_toggle: bool = True) -> Tuple[str, Dict]:
        """Generate complete HTML page"""
        # Generate color palette
        dark_palette = ColorPaletteGenerator.generate_palette(style)
        light_palette = ColorPaletteGenerator.get_light_palette(dark_palette)

        # Extract sections
        sections = HTMLPageBuilder.extract_sections(description)

        # Generate meta tags
        meta_tags = HTMLPageBuilder.generate_meta_tags(title, description)

        # Generate sections
        sections_html = '\n\n'.join([
            HTMLPageBuilder.generate_section_html(section, dark_palette)
            for section in sections
        ])

        # Generate navigation links based on sections
        nav_links = HTMLPageBuilder.generate_nav_links(sections)

        # Generate CSS (with both palettes)
        css = HTMLPageBuilder.generate_css(dark_palette, light_palette)

        # Generate theme toggle if requested
        toggle_html = HTMLPageBuilder.generate_theme_toggle_script() if include_toggle else ''

        # Build complete HTML
        html = f'''<!DOCTYPE html>
<html lang="en">
<head>
{meta_tags}
{css}
</head>
<body>
    <header>
        <nav>
            <h1>{title}</h1>
            <div>
                {nav_links}
            </div>
        </nav>
    </header>

    <main>
{sections_html}
    </main>

    {toggle_html}
</body>
</html>'''

        return html, dark_palette


# Global history
generation_history = []

def generate_html_page(title: str, description: str, style: str = "modern", include_toggle: bool = True) -> Tuple[str, str, str]:
    """Generate HTML page with styling"""
    if not title.strip() or not description.strip():
        return "", "❌ Please provide both title and description!", ""

    try:
        html_output, palette = HTMLGenerationEngine.generate_page(title, description, style, include_toggle)

        # Format color info
        color_info = f"""**Color Palette for '{style}' style:**

| Element | Color |
|---------|-------|
| Primary | {palette['primary']} |
| Secondary | {palette['secondary']} |
| Accent | {palette['accent']} |
| Background | {palette['background']} |
| Surface | {palette['surface']} |
| Text Primary | {palette['text_primary']} |
| Text Secondary | {palette['text_secondary']} |
| Border | {palette['border']} |"""

        # Add to history
        generation_history.append({
            'title': title,
            'description': description,
            'html': html_output,
            'palette': palette,
            'timestamp': datetime.now().isoformat()
        })

        return html_output, "✅ HTML page generated successfully!", color_info

    except Exception as e:
        return "", f"❌ Error: {str(e)}", ""

def get_color_swatches(style: str) -> str:
    """Return HTML with color swatches for the selected style"""
    try:
        palette = ColorPaletteGenerator.generate_palette(style)
        html = '<div style="display: grid; grid-template-columns: repeat(auto-fill, minmax(140px,1fr)); gap: 12px; margin-top: 20px;">'
        for name, color in palette.items():
            # Determine text color for contrast
            text_color = '#fff' if int(color[1:3],16) < 128 else '#000'
            html += f'<div style="background:{color}; padding: 16px 8px; border-radius: 12px; text-align: center; color:{text_color}; font-weight: 500; box-shadow: 0 4px 6px rgba(0,0,0,0.1);"><div style="font-size: 0.9rem; text-transform: capitalize;">{name}</div><div style="font-family: monospace; margin-top: 4px;">{color}</div></div>'
        html += '</div>'
        return html
    except Exception as e:
        return f"<p>Error: {e}</p>"

def preview_html(html_content: str) -> str:
    """Wrap HTML in an iframe for live preview"""
    if not html_content or not html_content.strip():
        return "<p style='text-align:center; color:#fff; padding:40px; background:#333; border-radius:10px;'>✨ No HTML to preview. Generate a page first in the 'Generate Page' tab!</p>"
    # Escape for srcdoc
    escaped = html.escape(html_content, quote=True)
    return f'<iframe srcdoc="{escaped}" style="width:100%; height:600px; border:none; border-radius:12px; box-shadow:0 10px 25px rgba(0,0,0,0.2);"></iframe>'

def load_saas_template():
    """Load SaaS template"""
    return (
        "SaaS Product",
        "Hero banner with SaaS product, features showcase with 3 items, pricing plans comparison with three tiers, testimonials from customers, contact form, and footer",
        "modern"
    )

def load_company_template():
    """Load company website template"""
    return (
        "Company Name",
        "Hero banner, about our company, services we offer, team members, contact information, and footer",
        "minimal"
    )

def load_portfolio_template():
    """Load portfolio website template"""
    return (
        "My Portfolio",
        "Hero section with name and tagline, portfolio gallery of creative work, about me section with skills, testimonials from clients, contact form, and footer",
        "creative"
    )


# ===== GRADIO INTERFACE =====
with gr.Blocks(theme=gr.themes.Soft(), title="HTML Quick-Styler Advanced") as demo:
    gr.Markdown("""
    # 🎨 HTML Quick-Styler Advanced
    ### Professional HTML Page Generator with Auto-Styling

    **Generate production-ready HTML pages in seconds** with intelligent section detection and beautiful color palettes.
    """)

    # State variable for generated HTML
    html_state = gr.State()

    with gr.Tabs():
        # TAB 1: Page Generator
        with gr.TabItem("📄 Generate Page"):
            with gr.Row():
                with gr.Column(scale=1):
                    gr.Markdown("### 📝 Page Details")
                    page_title = gr.Textbox(
                        label="Page Title",
                        value="Modern Portfolio Website",
                        lines=1,
                        placeholder="Enter your page title..."
                    )

                    page_description = gr.Textbox(
                        label="Page Description & Sections",
                        value="Hero section with welcome message, features list with 3 items, about section, portfolio gallery, testimonials from clients, pricing plans, contact form, and footer",
                        lines=4,
                        placeholder="Describe your page sections (hero, features, about, portfolio, testimonials, pricing, contact, footer)..."
                    )

                    color_style = gr.Dropdown(
                        ["modern", "vibrant", "ocean", "forest", "sunset", "luxury", "creative", "minimal"],
                        value="modern",
                        label="🎨 Color Style"
                    )

                    # Theme toggle option
                    include_toggle = gr.Checkbox(
                        label="🌗 Include dark/light mode toggle in page",
                        value=True
                    )

                    generate_btn = gr.Button("🚀 Generate HTML", size="lg", variant="primary")

                with gr.Column(scale=1):
                    gr.Markdown("### 💻 Generated Output")
                    html_output = gr.Code(
                        label="Generated HTML/CSS",
                        language="html",
                        lines=20,
                        interactive=True
                    )

                    with gr.Row():
                        status_msg = gr.Markdown("")

                    with gr.Row():
                        color_info = gr.Markdown("")

            def generate_and_update_state(title, desc, style, toggle):
                html, status, color = generate_html_page(title, desc, style, toggle)
                return html, status, color, html

            generate_btn.click(
                generate_and_update_state,
                inputs=[page_title, page_description, color_style, include_toggle],
                outputs=[html_output, status_msg, color_info, html_state]
            )

        # TAB 2: Live Preview (with iframe)
        with gr.TabItem("👁️ Live Preview"):
            gr.Markdown("### Live Preview of Your Generated Page")
            gr.Markdown("*The preview updates automatically when you generate a new page.*")

            preview_html_component = gr.HTML(
                value=preview_html(""),
                label="Live Preview"
            )

            # Auto-refresh preview when state changes
            def update_preview(html):
                return preview_html(html)

            html_state.change(
                update_preview,
                inputs=[html_state],
                outputs=[preview_html_component]
            )

        # TAB 3: Templates (with Portfolio)
        with gr.TabItem("📚 Templates"):
            gr.Markdown("""
            ### Quick Start Templates
            Click any template to auto-fill the generator form with pre-configured content.
            """)

            with gr.Row():
                with gr.Column():
                    gr.Markdown("""
                    #### 🚀 SaaS Product
                    Perfect for software-as-a-service products with pricing tiers and testimonials.
                    """)
                    saas_btn = gr.Button("Use SaaS Template", size="sm", variant="secondary")

                with gr.Column():
                    gr.Markdown("""
                    #### 🏢 Company Website
                    Ideal for corporate sites with team and services sections.
                    """)
                    company_btn = gr.Button("Use Company Template", size="sm", variant="secondary")

                with gr.Column():
                    gr.Markdown("""
                    #### 🎨 Portfolio
                    Great for creatives, photographers, and designers.
                    """)
                    portfolio_btn = gr.Button("Use Portfolio Template", size="sm", variant="secondary")

            # Template loader functions
            saas_btn.click(
                load_saas_template,
                outputs=[page_title, page_description, color_style]
            )

            company_btn.click(
                load_company_template,
                outputs=[page_title, page_description, color_style]
            )

            portfolio_btn.click(
                load_portfolio_template,
                outputs=[page_title, page_description, color_style]
            )

        # TAB 4: Color Studio (with swatches)
        with gr.TabItem("🎨 Color Studio"):
            gr.Markdown("""
            ### Explore Color Palettes
            Preview different color schemes before generating your page.
            """)

            with gr.Row():
                style_selector = gr.Radio(
                    ["modern", "vibrant", "ocean", "forest", "sunset", "luxury", "creative", "minimal"],
                    value="modern",
                    label="Choose Style to Preview",
                    interactive=True
                )

                palette_btn = gr.Button("🎨 Show Palette", size="lg", variant="primary")

            palette_display = gr.HTML()

            palette_btn.click(
                get_color_swatches,
                inputs=[style_selector],
                outputs=[palette_display]
            )

        # TAB 5: User Guide
        with gr.TabItem("📖 Guide"):
            gr.Markdown("""
            # 📖 HTML Quick-Styler Guide

            ## How It Works

            ### 1. Enter Your Details
            - **Title:** Your page name (appears in browser tab and header)
            - **Description:** Describe the sections you want (the AI detects keywords)
            - **Color Style:** Pick a theme that matches your brand
            - **Theme Toggle:** Optionally add a dark/light mode switch to your page

            ### 2. Automatic Section Detection
            The tool recognizes these keywords:

            | Keyword | Section Generated |
            |---------|------------------|
            | hero, banner, landing | Hero Section with CTA |
            | features, services, benefits | Features Grid (3 cards) |
            | about, team, company | About Section |
            | portfolio, gallery, work | Portfolio Gallery |
            | testimonial, reviews, feedback | Testimonials Grid |
            | pricing, plans, cost | Pricing Tables (3 tiers) |
            | contact, form, reach | Contact Form |
            | footer, bottom | Footer with links |

            ### 3. Features
            - ✅ **Responsive Design** - Works on all devices
            - ✅ **SEO Optimized** - Meta tags included
            - ✅ **Modern CSS** - Flexbox/Grid, animations, gradients
            - ✅ **Color Palettes** - 8 professionally designed themes
            - ✅ **Dark/Light Mode Toggle** - Built‑in theme switcher
            - ✅ **Live Iframe Preview** - See your page in action
            - ✅ **Color Swatches** - Visual palette explorer
            - ✅ **Accessibility** - Proper contrast and semantics

            ### 4. Tips for Best Results
            - Be specific about sections in your description
            - Mix and match keywords for complex layouts
            - Preview your page in the Live Preview tab
            - Use the Color Studio to experiment with themes
            - Copy the generated code to your project
            """)

# ===== LAUNCH =====
if __name__ == "__main__":
    demo.launch(
        server_name="127.0.0.1",
        # server_port removed so Gradio picks a free port automatically
        share=True
    )